main: de.raidcraft.rcfarms.RCFarmsPlugin
name: RCFarms
version: ${project.version}#${BUILDS_ALL_TIME}
description: Provides upgradable item farms.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API, WorldControlPlugina]
softdepend: [RCConversations]
database: true