settings:
  entity-metakeys:
    - 'FARM_GUARD'
  npc-name: 'Farmverwalter'
  npc-equipment:
    hand: PAPER
    chestplate: CHAINMAIL_CHESTPLATE
    leggings: LEATHER_LEGGINGS
    boots: LEATHER_BOOTS

stages:
  start:
    actions:
      A:
        type: FIND_FARM
        args:
          onfailure: destroy
      B:
        type: IS_FARM_OWNER
        args:
          onsuccess: is_owner
      C:
        type: IS_FARM_FOR_SALE
        args:
          onfailure: not_for_sale
    text: 'Hallo %name, wie kann ich dir helfen?'
    answers:
      1:
        text: 'Ich möchte diese Farm kaufen'
        actions:
          A:
            type: STAGE
            args:
              stage: confirm_buy
      2:


  destroy:
    actions:
      A:
        type: NPC_DESTROY
    text: 'Ich stehe hier falsch!'