settings:
  entity-metakeys:
    - 'FARM_GUARD'
  npc-name: 'Farmverwalter'
  npc-equipment:
    hand: PAPER
    chestplate: CHAINMAIL_CHESTPLATE
    leggings: LEATHER_LEGGINGS
    boots: LEATHER_BOOTS

stages:
  start:
    actions:
      A:
        type: FIND_FARM
        args:
          onfailure: destroy
      B:
        type: IS_FARM_OWNER
        args:
          onsuccess: is_owner
      C:
        type: IS_FARM_FOR_SALE
        args:
          onfailure: not_for_sale
    text: 'Hallo %name, diese Farm hier steht zum Verkauf!|Möchtest du sie für %[farm_price_formatted] kaufen?'
    answers:
      1:
        text: 'Ja, ich möchte sie verbindlich kaufen'
        actions:
          A:
            type: BUY_FARM
            args:
              farm-id: '%[farm_id]'
              onfailure: buy_errors
          B:
            type: TEXT
            args:
              text: 'Herzlichen Glückwunsch, du bist nun der Besitzer dieser Farm!'
      2:
        text: 'Nein'
        actions:
          A:
            type: TEXT
            args:
              text: 'Alles klar, einen schönen Tag wünsch ich dir!'

  buy_errors:
    text: '&4%[error]'

  not_for_sale:
    text: 'Diese Farm ist bereits im Besitz von %[farm_owner]!'

  destroy:
    actions:
      A:
        type: NPC_DESTROY
    text: 'Ich stehe hier falsch!'